// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_0ETUJm7QdwcJwF4MUsh8P3n7RBeNpA',
    appId: '1:268399764800:web:a80a41cff1ce8ce4bfc6a5',
    messagingSenderId: '268399764800',
    projectId: 'ditonton-382f3',
    authDomain: 'ditonton-382f3.firebaseapp.com',
    storageBucket: 'ditonton-382f3.appspot.com',
    measurementId: 'G-S5N1JM6ZS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkgaSlo7t2WJ8FeLn9CpOwMyE37Eyk0c',
    appId: '1:268399764800:android:ddf57047ca3eed07bfc6a5',
    messagingSenderId: '268399764800',
    projectId: 'ditonton-382f3',
    storageBucket: 'ditonton-382f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFRvwP9JIwttr1qrYKVT4QS5l06AndWlc',
    appId: '1:268399764800:ios:8d012a55d992030dbfc6a5',
    messagingSenderId: '268399764800',
    projectId: 'ditonton-382f3',
    storageBucket: 'ditonton-382f3.appspot.com',
    iosClientId: '268399764800-7dc7t6hp8jjitv9aj24vj90ce4b028vv.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
