// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVouvfywc9uXydxH2H3TRMRoHeZq2B-NE',
    appId: '1:179231310704:web:4aad78b9fae36499e205b5',
    messagingSenderId: '179231310704',
    projectId: 'ditonton-7ba07',
    authDomain: 'ditonton-7ba07.firebaseapp.com',
    storageBucket: 'ditonton-7ba07.appspot.com',
    measurementId: 'G-14HC5TK2XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnexQR_0Y2LG7JdK3sAQR5ahyyU4o-g40',
    appId: '1:179231310704:android:4a4de3f7b27acbc9e205b5',
    messagingSenderId: '179231310704',
    projectId: 'ditonton-7ba07',
    storageBucket: 'ditonton-7ba07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOrHGeg2Ix1-B_hDEg5nF2EF29Xn2-LFg',
    appId: '1:179231310704:ios:4b0986240dadbe2ae205b5',
    messagingSenderId: '179231310704',
    projectId: 'ditonton-7ba07',
    storageBucket: 'ditonton-7ba07.appspot.com',
    iosClientId:
        '179231310704-pp7715jub86sral6etfcuog6hhb2lld9.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
